services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: dockerfiles/web.dockerfile
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
     - ./web:/app
     - ./web/node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
