apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpsons-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: simpsons
  template:
    metadata:
      labels:
        app: simpsons
    spec:
      containers:
        - name: simpsons
          image: michael10098/simpsons-web:latest
