services:
  python:
    container_name: python
    build:
      context: .
      dockerfile: dockerfiles/python.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./python:/app
  web:
    build:
      context: .
      dockerfile: dockerfiles/web.dockerfile
    ports:
      - "3000:3000"
    volumes:
     - ./web:/app
     - ./web/node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: node server.js
    depends_on:
      - python
